python/lab15/app/todo/models.py
from sqlalchemy import Integer, String, Boolean, Date
from sqlalchemy.orm import Mapped, mapped_column
from datetime import date
from ..extensions import db

class Todo(db.Model):
    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    title: Mapped[str] = mapped_column(String(100))
    due_date: Mapped[date] = mapped_column(Date, nullable=True) 
    complete: Mapped[bool] = mapped_column(Boolean)
    category_id: Mapped[int] = mapped_column(Integer, db.ForeignKey('category.id', name='fk_category'), nullable=True)

class Category(db.Model):
    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    name: Mapped[str] = mapped_column(String)
    todos = db.relationship('Todo', backref='category')

python/lab15/app/todo/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, DateField, SelectField
from wtforms.validators import DataRequired

class TodoForm(FlaskForm):
    title = StringField(label='Title', validators=[DataRequired("Title is required")])
    due_date = DateField(label='Due date')
    categories = SelectField(label="Category", coerce=int)
    submit = SubmitField(label="Save")

class CategoryForm(FlaskForm):
    name = StringField(label='Name', validators=[DataRequired("Name is required")])
    submit = SubmitField(label="Add new category")

python/lab15/app/todo/__init__.py
from flask import Blueprint

todo_bp = Blueprint('todo', __name__, template_folder='templates')

python/lab15/app/todo/views.py
from flask import render_template, redirect, url_for, flash
from ..extensions import db
from .forms import TodoForm, CategoryForm
from .models import Todo, Category
from . import todo_bp


@todo_bp.route('/', methods=["GET"])
def todo_page():
    form=TodoForm()
    form.categories.choices = [(c.id, c.name) for c in Category.query.all()] 
    return render_template("todo/todo.html", todo_list=Todo.query.all(), form=form)
 
@todo_bp.route("/", methods=["POST"])
def add():
    form=TodoForm()

    new_todo = Todo(
        title = form.title.data, 
        due_date = form.due_date.data, 
        category_id = form.categories.data,
        complete = False
    )
    try: 
        db.session.add(new_todo)
        db.session.commit()
        flash('Todo added!', category='success')
    except:
        db.session.rollback()
        flash('Error!', category='danger')
    return redirect(url_for("todo.todo_page"))
 
@todo_bp.route("/update/<int:id>")
def update(id):
    todo = Todo.query.get_or_404(id)
    todo.complete = not todo.complete   
    try: 
        db.session.commit()
        flash(f'Todo({todo.id}) updated!', category='success')
    except:
        db.session.rollback()
        flash('Error!', category='danger')    
    return redirect(url_for("todo.todo_page"))
 
@todo_bp.route("/delete/<int:id>")
def delete(id):
    todo = Todo.query.get_or_404(id)
    try: 
        db.session.delete(todo)
        db.session.commit()
        flash(f'Todo({todo.id}) deleted!', category='success')
    except:
        db.session.rollback()
        flash('Error!', category='danger')    
    return redirect(url_for("todo.todo_page"))


@todo_bp.route('/categories', methods=["GET"])
def category_page():
    return render_template("todo/categories.html", categories=Category.query.all(), form=CategoryForm())

@todo_bp.route("/categories", methods=["POST"])
def add_category():
    form=CategoryForm()
    
    if form.validate_on_submit():
        new_category = Category(name = form.name.data)
        try:
            db.session.add(new_category)
            db.session.commit()
            flash(f'Category({new_category.name}) created!', category='success')
        except:
            flash('Error!', category='danger')
            db.session.rollback()
    else:
        flash('Invalid form!', category='danger')

    return redirect(url_for('todo.category_page'))

@todo_bp.route("/categories/delete/<int:id>", methods=["POST"])
def delete_category(id):
    category = Category.query.get_or_404(id)
    try:
        db.session.delete(category)
        db.session.commit()
        flash(f'Category({category.id}) deleted!', category='success')
    except:
        flash('Error!', category='danger')
        db.session.rollback()
    return redirect(url_for("todo.category_page"))

python/lab15/app/todo/templates/todo/categories.html
{% extends "base.html" %}
{% from "_render-field.html" import render_field %}
{% block title %}Todo{% endblock %}
{% block content %}
<div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col col-lg-9 col-xl-10">
            <div class="card rounded-3">
                <div class="card-body p-4">
                    <div class="text-center my-3">
                        <h4 class="mb-4">Categories</h4>
                        <a href="{{url_for('todo.todo_page')}}" class="btn btn-primary mt-4">Todo</a>
                    </div>
                    <div class="row justify-content-between mt-5">
                        <form class="col-6" action="{{url_for('todo.add_category')}}" method="post" novalidate>
                            {{ form.csrf_token }}
                            <div class="form-group">
                                {{ render_field(form.name, class="form-control") }}
                            </div>
                            <div class="form-group">
                                {{ render_field(form.submit, class="btn btn-primary w-100 mt-3") }}
                            </div>
                        </form>
                        <ul class="col-5 list-group">
                            {% for category in categories %}
                                <li class="list-group-item d-flex justify-content-between align-items-center mb-3">
                                    <span>{{category.name}}</span>
                                    <div class="d-flex align-items-center">
                                        <span class="badge bg-primary rounded-pill me-3">{{category.todos|length}}</span>
                                        <form method="POST" action="{{url_for('todo.delete_category', id=category.id)}}">
                                            <button type="submit" class="btn btn-danger btn-sm">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3-fill" viewBox="0 0 16 16">
                                                    <path d="M11 1.5v1h3.5a.5.5 0 0 1 0 1h-.538l-.853 10.66A2 2 0 0 1 11.115 16h-6.23a2 2 0 0 1-1.994-1.84L2.038 3.5H1.5a.5.5 0 0 1 0-1H5v-1A1.5 1.5 0 0 1 6.5 0h3A1.5 1.5 0 0 1 11 1.5Zm-5 0v1h4v-1a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5ZM4.5 5.029l.5 8.5a.5.5 0 1 0 .998-.06l-.5-8.5a.5.5 0 1 0-.998.06Zm6.53-.528a.5.5 0 0 0-.528.47l-.5 8.5a.5.5 0 0 0 .998.058l.5-8.5a.5.5 0 0 0-.47-.528ZM8 4.5a.5.5 0 0 0-.5.5v8.5a.5.5 0 0 0 1 0V5a.5.5 0 0 0-.5-.5Z"></path>
                                                </svg>
                                            </button>
                                        </form>
                                    </div>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

python/lab15/app/todo/templates/todo/todo.html
{% extends "base.html" %}
{% from "_render-field.html" import render_field %}
{% block title %}Todo{% endblock %}
{% block content %}
<div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col col-lg-9 col-xl-10">
            <div class="card rounded-3">
                <div class="card-body p-4">

                    <div class="text-center my-3 pb-3">
                        <h4 class="fw-bold">Simple To Do</h4>
                        <a href="{{url_for('todo.category_page')}}" class="btn btn-primary mb-4">Categories</a>
                    </div>

                    <form class="row justify-content-center" method="post">
                        {{ form.csrf_token }}
                        <div class="col-3">
                            {{ render_field(form.title, class="form-control") }}
                        </div>
                        <div class="col-2">
                            {{ render_field(form.due_date, class="form-control") }}
                        </div>
                        <div class="col-2">
                            {{ render_field(form.categories, class="form-select") }}
                        </div>
                        <div class="col-1">
                            {{ render_field(form.submit, class="btn btn-primary w-100") }}
                        </div>
                    </form>

                    <table class="table mb-4 mt-5 text-center">
                        <thead>
                            <tr>
                                <th scope="col">No.</th>
                                <th scope="col">Todo item</th>
                                <th scope="col">Due date</th>
                                <th scope="col">Category</th>
                                <th scope="col">Status</th>
                                <th scope="col">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for todo in todo_list %}
                            <tr>
                                <th scope="row">{{todo.id }}</th>
                                <td>{{ todo.title }}</td>
                                <td>
                                    {% if todo.due_date %}
                                        {{ todo.due_date }}
                                    {% else %}
                                        -
                                    {% endif %}
                                </td>
                                <td>
                                    {% if todo.category %}
                                        {{ todo.category.name }}
                                    {% else %}
                                        -
                                    {% endif %}
                                </td>
                                <td>
                                    {% if todo.complete == False %}
                                    <div class="badge bg-secondary">In progress</div>
                                    {% else %}
                                    <div class="badge bg-success">Completed</div>
                                    {% endif %}
                                </td>
                                <td>
                                    <a class="btn btn-success" href="{{url_for('todo.update', id=todo.id)}}">Update</a>
                                    <a class="btn btn-danger ms-1" href="{{url_for('todo.delete', id=todo.id)}}">Delete</a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}