python/lab15/app/feedbacks/models.py
from sqlalchemy import Integer, String, DateTime
from sqlalchemy.orm import Mapped, mapped_column
from datetime import datetime
from ..extensions import db


class Feedback(db.Model):
    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    user_email: Mapped[str] = mapped_column(String)
    topic: Mapped[str] = mapped_column(String)
    text: Mapped[str] = mapped_column(String)
    mark: Mapped[int] = mapped_column(Integer)
    date: Mapped[datetime] = mapped_column(DateTime) 

python/lab15/app/feedbacks/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, EmailField, TextAreaField, RadioField
from wtforms.validators import DataRequired


class FeedbackForm(FlaskForm):
    text = TextAreaField(label='Text', validators=[DataRequired("Text is required")])
    topic = StringField(label='Topic', validators=[DataRequired("Topic is required")])
    mark =  RadioField(choices=[('1','1'),('2','2'),('3','3'),('4','4'),('5','5')],
                       validators=[DataRequired("Mark is required")])
    email = EmailField(label='User email', validators=[DataRequired("Email is required")])
    submit = SubmitField(label="Save")

python/lab15/app/feedbacks/__init__.py
from flask import Blueprint

feedbacks_bp = Blueprint('feedbacks', __name__, template_folder='templates')

python/lab15/app/feedbacks/views.py
from flask import render_template, redirect, url_for, flash
from datetime import datetime
from ..extensions  import db
from .forms import FeedbackForm
from .models import Feedback
from . import feedbacks_bp


@feedbacks_bp.route('/', methods=["GET", "POST"])
def feedbacks():
    form=FeedbackForm()

    if form.validate_on_submit():
        new_feedback = Feedback(
            topic= form.topic.data,
            text=form.text.data,
            mark=form.mark.data,
            user_email=form.email.data,  
            date=datetime.now())
        
        try:
            db.session.add(new_feedback)
            db.session.commit()
            flash("Feedback added!", category="success")
        except:
            db.session.rollback()
            flash("Something went wrong!", category="danger")
        return redirect(url_for("feedbacks.feedbacks"))

    feedbacks = Feedback.query.all()
    return render_template("feedbacks/feedbacks.html", feedbacks=feedbacks, form=form)
 
@feedbacks_bp.route("/delete/<int:id>")
def delete(id):
    feedback = Feedback.query.get_or_404(id)
    try:
        db.session.delete(feedback)
        db.session.commit()
        flash("Feedback deleted!", category="success")
    except:
        db.session.rollback()
        flash("Something went wrong!", category="danger")
    
    return redirect(url_for("feedbacks.feedbacks"))

python/lab15/app/feedbacks/templates/feedbacks/feedbacks.html
{% extends "base.html" %}
{% from "_render-field.html" import render_field %}
{% block title %}Feedbacks{% endblock %}
{% block content %}
    <section class="top mt-5 ">
        <h1>Feedback form</h1>
        <form class="" action="{{url_for('feedbacks.feedbacks')}}" method="post" novalidate>
            {{ form.csrf_token }}
            <div class="row">
                <div class="form-section">
                    <div class="form-group">
                        {{ render_field(form.topic, class="form-control") }}
                    </div>
                    <div class="form-group mt-3">
                        {{ render_field(form.text, class="form-control", style="height: 128px;") }}
                    </div>
                </div>
                <div class="form-section">
                    <div class="form-group">
                        {{ render_field(form.email, class="form-control") }}
                    </div>
                    <div class="form-group mt-3">
                        {{ render_field(form.mark, class="form-check-input") }}
                    </div>
                </div>
            </div>
            <div class="form-group mt-4">
                {{ render_field(form.submit, class="btn btn-primary") }}
            </div>
      </form>
    </section>
    <p class="text-end">Total: {{feedbacks|length}}</p>
    <section class="list mt-5">
        {% for feedback in feedbacks %}
            <div class="card mt-2" style="width: 80%; margin:0 auto">
                <div class="card-body" >
                    <div style="display: flex; justify-content: space-between;">
                        <h4 class="card-title">{{feedback.topic}}</h4>
                        <div>Rating: {{feedback.mark}}</div>
                    </div>
                    <h6 class="card-subtitle mb-2 text-muted">{{feedback.user_email}}</h6>
                    <p class="card-text">{{feedback.text}}</p>
                    <p class="card-subtitle mb-2 text-muted">{{feedback.date.strftime('%Y-%m-%d %H:%M:%S')}}</p>
                    <a class="card-link" href="{{url_for('feedbacks.delete', id=feedback.id)}}">Delete</a>
                </div>
            </div>
        {% endfor %}
    </section>
{% endblock %}