python/lab15/app/cookies/__init__.py
from flask import Blueprint

cookies_bp = Blueprint('cookies', __name__, template_folder='templates')

python/lab15/app/cookies/views.py
from flask import render_template, request, redirect, url_for, make_response, flash
from flask_login import login_required
from datetime import datetime
from . import cookies_bp


@cookies_bp.route('/')
@login_required
def info_page():
    return render_template('cookies/info.html', cookies=request.cookies)

@cookies_bp.route('/', methods=["POST"])
@login_required
def add():
    key = request.form.get("key")
    value = request.form.get("value")
    exp_date = request.form.get("date")

    if key and value and exp_date:
        response = make_response(redirect(url_for("cookies.info_page")))
        response.set_cookie(key, value, expires=datetime.strptime(exp_date, "%Y-%m-%dT%H:%M"))
        flash(f"Success! {key} : {value} was added.", category="success")
        return response

    flash("Failed!", category="danger")
    return redirect(url_for("cookies.info_page"))

@cookies_bp.route('/delete', methods=["POST"])
@cookies_bp.route('/delete/<key>', methods=["POST"])
@login_required
def delete(key = None):
    response = make_response(redirect(url_for("cookies.info_page")))

    if key:
        response.delete_cookie(key)
        flash(f"Success! Cookie: {key} was deleted.", category="success")
    else:
        for key in request.cookies.keys():
            response.delete_cookie(key)
    
    return response

python/lab15/app/cookies/templates/cookies/info.html
{% extends "base.html" %}
{% from "_render-field.html" import render_field %}
{% block title %}Info{% endblock %}
{% block content %}
    <div class="row align-items-center justify-content-between" style="margin-top: 100px;">
        <h1 class="col-auto">Hello, {{current_user.username}}!</h1>
    </div>
    <div style="margin-top: 80px;">
            <div class="row align-items-center justify-content-end">
                <form  method="POST" action="{{url_for('cookies.add')}}" class="col-auto align-items-center row">
                    <div class="col-auto">
                      <input name="key" type="text" class="form-control" id="key" placeholder="Key">
                    </div>
                    <div class="col-auto">
                      <input name="value" type="text" class="form-control" id="value" placeholder="Value">
                    </div>
                    <div class="col-auto">
                        <input class="form-control" name="date" type="datetime-local">
                      </div>
                    <div class="col-auto">
                      <button type="submit" class="btn btn-primary">
                           Add
                           <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus-lg" viewBox="0 0 16 16">
                              <path fill-rule="evenodd" d="M8 2a.5.5 0 0 1 .5.5v5h5a.5.5 0 0 1 0 1h-5v5a.5.5 0 0 1-1 0v-5h-5a.5.5 0 0 1 0-1h5v-5A.5.5 0 0 1 8 2Z"/>
                          </svg>
                      </button>
                    </div>

                  </form>
                  <form class="col-auto" method="POST" action="{{url_for('cookies.delete')}}">
                    <button type="submit" class="btn btn-danger">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3-fill" viewBox="0 0 16 16">
                            <path d="M11 1.5v1h3.5a.5.5 0 0 1 0 1h-.538l-.853 10.66A2 2 0 0 1 11.115 16h-6.23a2 2 0 0 1-1.994-1.84L2.038 3.5H1.5a.5.5 0 0 1 0-1H5v-1A1.5 1.5 0 0 1 6.5 0h3A1.5 1.5 0 0 1 11 1.5Zm-5 0v1h4v-1a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5ZM4.5 5.029l.5 8.5a.5.5 0 1 0 .998-.06l-.5-8.5a.5.5 0 1 0-.998.06Zm6.53-.528a.5.5 0 0 0-.528.47l-.5 8.5a.5.5 0 0 0 .998.058l.5-8.5a.5.5 0 0 0-.47-.528ZM8 4.5a.5.5 0 0 0-.5.5v8.5a.5.5 0 0 0 1 0V5a.5.5 0 0 0-.5-.5Z"></path>
                        </svg>
                        Delete All
                   </button>
                </form>
            </div>
    </div>
    <table class="table" style="word-break: break-word;">
        <thead>
          <tr>
            <th scope="col">Key</th>
            <th scope="col">Value</th>
            <th scope="col">Action</th>
          </tr>
        </thead>
        <tbody>
          {% for key, value in cookies.items() %}
            <tr>
                <td>{{key}}</td>
                <td>{{value}}</td>
                <td> <form method="POST" action="{{url_for('cookies.delete', key=key)}}">
                    <button type="submit" class="btn btn-outline-danger">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3-fill" viewBox="0 0 16 16">
                            <path d="M11 1.5v1h3.5a.5.5 0 0 1 0 1h-.538l-.853 10.66A2 2 0 0 1 11.115 16h-6.23a2 2 0 0 1-1.994-1.84L2.038 3.5H1.5a.5.5 0 0 1 0-1H5v-1A1.5 1.5 0 0 1 6.5 0h3A1.5 1.5 0 0 1 11 1.5Zm-5 0v1h4v-1a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5ZM4.5 5.029l.5 8.5a.5.5 0 1 0 .998-.06l-.5-8.5a.5.5 0 1 0-.998.06Zm6.53-.528a.5.5 0 0 0-.528.47l-.5 8.5a.5.5 0 0 0 .998.058l.5-8.5a.5.5 0 0 0-.47-.528ZM8 4.5a.5.5 0 0 0-.5.5v8.5a.5.5 0 0 0 1 0V5a.5.5 0 0 0-.5-.5Z"></path>
                        </svg>
                        Delete
                    </button>
                </form></td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
{% endblock %}